tls:
  certificates:
    - certFile: /etc/traefik/certs/local.crt
      keyFile: /etc/traefik/certs/local.key

  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/local.crt
        keyFile: /etc/traefik/certs/local.key

http:
  routers:
    # Dashboard
    traefik:
      rule: "Host(`traefik.home.local`)"
      entryPoints:
        - websecure
      service: api@internal
      tls: {}

    # Homepage
    homarr:
      rule: "Host(`home.local`)"
      entryPoints:
        - websecure
      service: homarr
      tls: {}

    # Media Servers
    jellyfin:
      rule: "Host(`jellyfin.home.local`)"
      entryPoints:
        - websecure
      service: jellyfin
      tls: {}

    plex:
      rule: "Host(`plex.home.local`)"
      entryPoints:
        - websecure
      service: plex
      tls: {}

    # Request Management
    jellyseerr:
      rule: "Host(`jellyseerr.home.local`)"
      entryPoints:
        - websecure
      service: jellyseerr
      tls: {}

    # Arr Stack
    sonarr:
      rule: "Host(`sonarr.home.local`)"
      entryPoints:
        - websecure
      service: sonarr
      tls: {}

    radarr:
      rule: "Host(`radarr.home.local`)"
      entryPoints:
        - websecure
      service: radarr
      tls: {}

    bazarr:
      rule: "Host(`bazarr.home.local`)"
      entryPoints:
        - websecure
      service: bazarr
      tls: {}

    prowlarr:
      rule: "Host(`prowlarr.home.local`)"
      entryPoints:
        - websecure
      service: prowlarr
      tls: {}

    # Download Clients
    qbittorrent:
      rule: "Host(`qbittorrent.home.local`)"
      entryPoints:
        - websecure
      service: qbittorrent
      tls: {}

    sabnzbd:
      rule: "Host(`sabnzbd.home.local`)"
      entryPoints:
        - websecure
      service: sabnzbd
      tls: {}

    # Transcoding
    tdarr:
      rule: "Host(`tdarr.home.local`)"
      entryPoints:
        - websecure
      service: tdarr
      tls: {}

    # Utilities
    unpackerr:
      rule: "Host(`unpackerr.home.local`)"
      entryPoints:
        - websecure
      service: unpackerr
      tls: {}

    flaresolverr:
      rule: "Host(`flaresolverr.home.local`)"
      entryPoints:
        - websecure
      service: flaresolverr
      tls: {}

    # Infrastructure
    portainer:
      rule: "Host(`portainer.home.local`)"
      entryPoints:
        - websecure
      service: portainer
      tls: {}

    adguard:
      rule: "Host(`adguard.home.local`)"
      entryPoints:
        - websecure
      service: adguard
      tls: {}

    # Applications
    recipes:
      rule: "Host(`recipes.home.local`)"
      entryPoints:
        - websecure
      service: recipes
      tls: {}

    n8n:
      rule: "Host(`n8n.home.local`)"
      entryPoints:
        - websecure
      service: n8n
      tls: {}

    # Custom
    vert:
      rule: "Host(`vert.home.local`)"
      entryPoints:
        - websecure
      service: vert
      tls: {}

    vertd:
      rule: "Host(`vertd.home.local`)"
      entryPoints:
        - websecure
      service: vertd
      tls: {}

  services:
    homarr:
      loadBalancer:
        servers:
          - url: "http://homarr:7575"

    jellyfin:
      loadBalancer:
        servers:
          - url: "http://jellyfin:8096"

    plex:
      loadBalancer:
        servers:
          - url: "http://plex:32400"

    jellyseerr:
      loadBalancer:
        servers:
          - url: "http://jellyseerr:5055"

    sonarr:
      loadBalancer:
        servers:
          - url: "http://sonarr:8989"

    radarr:
      loadBalancer:
        servers:
          - url: "http://radarr:7878"

    bazarr:
      loadBalancer:
        servers:
          - url: "http://bazarr:6767"

    prowlarr:
      loadBalancer:
        servers:
          - url: "http://prowlarr:9696"

    qbittorrent:
      loadBalancer:
        servers:
          - url: "http://qbittorrent:8200"

    sabnzbd:
      loadBalancer:
        servers:
          - url: "http://sabnzbd:8080"

    tdarr:
      loadBalancer:
        servers:
          - url: "http://tdarr:8265"

    unpackerr:
      loadBalancer:
        servers:
          - url: "http://unpackerr:5656"

    flaresolverr:
      loadBalancer:
        servers:
          - url: "http://flaresolverr:8191"

    portainer:
      loadBalancer:
        servers:
          - url: "http://portainer:9000"

    adguard:
      loadBalancer:
        servers:
          - url: "http://adguardhome:80"

    recipes:
      loadBalancer:
        servers:
          - url: "http://tandoor:8080"

    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

    vert:
      loadBalancer:
        servers:
          - url: "http://vert:80"

    vertd:
      loadBalancer:
        servers:
          - url: "http://vertd:24153"
